P = tf([4],[1 3.5 1.5]);
PID = tf([1.738 3.167 2.43],[1 0]);
display(P);
display(PID);
L = PID*P;
display(L);
T = feedback(L,1);
TD = 1/(1+L);
TD1 = P/(1+L);
TYN = -L/(1+L);
display(T);
display(TD);
display(TD1);
display(TYN);
figure('Name',"T and TYN");
hold on;
title("T and TYN");
bodeplot(T);
bodeplot(TYN);
hold off;
figure('Name',"TD and TD1");
hold on;
title("TD1 and TYN");
bodeplot(TD);
bodeplot(TD1);
hold off;